name: Test Workflow 2
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Test message'
        required: true
        default: 'Hello'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "${{ github.event.inputs.message }}"
